=begin
#ShipCompliant Connect

#ShipCompliant REST API supporting eCommerce and Point of Sale workflows. <br /> * required fields.

The version of the OpenAPI document: v1
Contact: shipcompliantsupport@sovos.com
Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'date'
require 'time'

module OpenapiClient
  class ShipCompliantRestAPIDomainsWholesaleEntitiesShipment
    attr_accessor :default_warehouse

    attr_accessor :freight

    attr_accessor :ship_date

    attr_accessor :shipment_items

    attr_accessor :shipment_key

    attr_accessor :shipment_reserved

    attr_accessor :shipping_customer_key

    attr_accessor :shipping_service

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'default_warehouse' => :'defaultWarehouse',
        :'freight' => :'freight',
        :'ship_date' => :'shipDate',
        :'shipment_items' => :'shipmentItems',
        :'shipment_key' => :'shipmentKey',
        :'shipment_reserved' => :'shipmentReserved',
        :'shipping_customer_key' => :'shippingCustomerKey',
        :'shipping_service' => :'shippingService'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'default_warehouse' => :'String',
        :'freight' => :'Float',
        :'ship_date' => :'Time',
        :'shipment_items' => :'Array<ShipCompliantRestAPIDomainsWholesaleEntitiesShipmentItem>',
        :'shipment_key' => :'String',
        :'shipment_reserved' => :'String',
        :'shipping_customer_key' => :'String',
        :'shipping_service' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'default_warehouse',
        :'shipment_key',
        :'shipment_reserved',
        :'shipping_service'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::ShipCompliantRestAPIDomainsWholesaleEntitiesShipment` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::ShipCompliantRestAPIDomainsWholesaleEntitiesShipment`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'default_warehouse')
        self.default_warehouse = attributes[:'default_warehouse']
      end

      if attributes.key?(:'freight')
        self.freight = attributes[:'freight']
      end

      if attributes.key?(:'ship_date')
        self.ship_date = attributes[:'ship_date']
      else
        self.ship_date = nil
      end

      if attributes.key?(:'shipment_items')
        if (value = attributes[:'shipment_items']).is_a?(Array)
          self.shipment_items = value
        end
      else
        self.shipment_items = nil
      end

      if attributes.key?(:'shipment_key')
        self.shipment_key = attributes[:'shipment_key']
      end

      if attributes.key?(:'shipment_reserved')
        self.shipment_reserved = attributes[:'shipment_reserved']
      end

      if attributes.key?(:'shipping_customer_key')
        self.shipping_customer_key = attributes[:'shipping_customer_key']
      else
        self.shipping_customer_key = nil
      end

      if attributes.key?(:'shipping_service')
        self.shipping_service = attributes[:'shipping_service']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @ship_date.nil?
        invalid_properties.push('invalid value for "ship_date", ship_date cannot be nil.')
      end

      if @shipment_items.nil?
        invalid_properties.push('invalid value for "shipment_items", shipment_items cannot be nil.')
      end

      if @shipping_customer_key.nil?
        invalid_properties.push('invalid value for "shipping_customer_key", shipping_customer_key cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @ship_date.nil?
      return false if @shipment_items.nil?
      return false if @shipping_customer_key.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          default_warehouse == o.default_warehouse &&
          freight == o.freight &&
          ship_date == o.ship_date &&
          shipment_items == o.shipment_items &&
          shipment_key == o.shipment_key &&
          shipment_reserved == o.shipment_reserved &&
          shipping_customer_key == o.shipping_customer_key &&
          shipping_service == o.shipping_service
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [default_warehouse, freight, ship_date, shipment_items, shipment_key, shipment_reserved, shipping_customer_key, shipping_service].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
