=begin
#ShipCompliant Connect

#ShipCompliant REST API supporting eCommerce and Point of Sale workflows. <br /> * required fields.

The version of the OpenAPI document: v1
Contact: shipcompliantsupport@sovos.com
Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::AddressesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AddressesApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::AddressesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AddressesApi' do
    it 'should create an instance of AddressesApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::AddressesApi)
    end
  end

  # unit tests for api_v1_addresses_validate_post
  # Validates the provided address
  # Sample request:                    POST /api/v1/addresses/validate      {          \&quot;Address\&quot;: {              \&quot;City\&quot;: \&quot;Boulder\&quot;,              \&quot;Company\&quot;: \&quot;Sovos\&quot;,              \&quot;Country\&quot;: \&quot;US\&quot;,              \&quot;County\&quot;: \&quot;Boulder\&quot;,              \&quot;DateOfBirth\&quot;: \&quot;1970-01-01T00:00:00Z\&quot;,              \&quot;Email\&quot;: \&quot;example@sovos.com\&quot;,              \&quot;Fax\&quot;: \&quot;555-555-5555\&quot;,              \&quot;FirstName\&quot;: \&quot;Test First Name\&quot;,              \&quot;LastName\&quot;: \&quot;Test Last Name\&quot;,              \&quot;Phone\&quot;: \&quot;555-555-5555\&quot;,              \&quot;State\&quot;: \&quot;CO\&quot;,              \&quot;Street1\&quot;: \&quot;2465 Central Ave\&quot;,              \&quot;Street2\&quot;: \&quot;Ste 110\&quot;,              \&quot;Zip1\&quot;: \&quot;80301\&quot;,              \&quot;Zip2\&quot;: \&quot;5728\&quot;           }      }
  # @param [Hash] opts the optional parameters
  # @option opts [ShipCompliantRestAPIDomainsAddressesEntitiesAddressBase] :ship_compliant_rest_api_domains_addresses_entities_address_base The request body with the address to be validated
  # @return [ShipCompliantRestAPIMiddlewaresSwaggerResponseTypesValidateAddressResponse]
  describe 'api_v1_addresses_validate_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
