=begin
#ShipCompliant Connect

#ShipCompliant REST API supporting eCommerce and Point of Sale workflows. <br /> * required fields.

The version of the OpenAPI document: v1
Contact: shipcompliantsupport@sovos.com
Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::BrandsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BrandsApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::BrandsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BrandsApi' do
    it 'should create an instance of BrandsApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::BrandsApi)
    end
  end

  # unit tests for api_v1_brands_brand_key_get
  # Retrieves brand information
  # Sample request:                    GET /api/v1/brands/BRAND123
  # @param brand_key The brand key
  # @param [Hash] opts the optional parameters
  # @return [ShipCompliantRestAPIMiddlewaresSwaggerResponseTypesGetBrandSuccessResponse]
  describe 'api_v1_brands_brand_key_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_brands_brand_key_put
  # Updates an existing brand
  # Sample request:                    PUT /api/v1/brands/BRAND123      {        \&quot;Key\&quot;: \&quot;BRAND123\&quot;,        \&quot;TTBBrandKey\&quot;: \&quot;TTBBrandKey\&quot;,        \&quot;Name\&quot;: \&quot;Example Brand\&quot;,        \&quot;Owner\&quot;: {          \&quot;City\&quot;: \&quot;Boulder\&quot;,          \&quot;Country\&quot;: \&quot;US\&quot;,          \&quot;Name\&quot;: \&quot;Example Owner\&quot;,          \&quot;State\&quot;: \&quot;CO\&quot;,          \&quot;Street1\&quot;: \&quot;2465 Central Ave\&quot;,          \&quot;Street2\&quot;: \&quot;Ste 110\&quot;,          \&quot;Zip\&quot;: \&quot;80301\&quot;        },        \&quot;ThisBrandIsBottledByAThirdParty\&quot;: true,        \&quot;ThisBrandIsProducedByAThirdParty\&quot;: true,        \&quot;ThisBrandOperatesUnderATradeName\&quot;: true,        \&quot;ThisBrandWasAcquiredFromAThirdParty\&quot;: false      }
  # @param brand_key The brand key
  # @param [Hash] opts the optional parameters
  # @option opts [ShipCompliantRestAPIDomainsBrandEntitiesBrand] :ship_compliant_rest_api_domains_brand_entities_brand The new Brand data
  # @return [ShipCompliantRestAPIMiddlewaresSwaggerResponseTypesPutBrandResponse]
  describe 'api_v1_brands_brand_key_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_brands_post
  # Adds a new brand
  # Sample request:                     POST /api/v1/brands      {          \&quot;Key\&quot;: \&quot;BRAND123\&quot;,          \&quot;TTBBrandKey\&quot;: \&quot;TTBBrandKey\&quot;,          \&quot;Name\&quot;: \&quot;Example Brand\&quot;,          \&quot;Owner\&quot;: {              \&quot;City\&quot;: \&quot;Boulder\&quot;,              \&quot;Country\&quot;: \&quot;US\&quot;,              \&quot;Name\&quot;: \&quot;Example Owner\&quot;,              \&quot;State\&quot;: \&quot;CO\&quot;,              \&quot;Street1\&quot;: \&quot;2465 Central Ave\&quot;,              \&quot;Street2\&quot;: \&quot;Ste 110\&quot;,              \&quot;Zip\&quot;: \&quot;80301\&quot;           },          \&quot;ThisBrandIsBottledByAThirdParty\&quot;: true,          \&quot;ThisBrandIsProducedByAThirdParty\&quot;: true,          \&quot;ThisBrandOperatesUnderATradeName\&quot;: true,          \&quot;ThisBrandWasAcquiredFromAThirdParty\&quot;: false      }
  # @param [Hash] opts the optional parameters
  # @option opts [ShipCompliantRestAPIDomainsBrandEntitiesPostBrand] :ship_compliant_rest_api_domains_brand_entities_post_brand The new Brand
  # @return [ShipCompliantRestAPIMiddlewaresSwaggerResponseTypesPostBrandResponse]
  describe 'api_v1_brands_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
