=begin
#ShipCompliant Connect

#ShipCompliant REST API supporting eCommerce and Point of Sale workflows. <br /> * required fields.

The version of the OpenAPI document: v1
Contact: shipcompliantsupport@sovos.com
Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::HoldLocationsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'HoldLocationsApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::HoldLocationsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of HoldLocationsApi' do
    it 'should create an instance of HoldLocationsApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::HoldLocationsApi)
    end
  end

  # unit tests for api_v1_hold_locations_carrier_get
  # Gets hold locations for an address within a specified radius
  # Sample request:                 GET /api/v1/holdLocations/FedEx?zipCode&#x3D;80301&amp;streetAddress&#x3D;2465+Central+Ave&amp;city&#x3D;Boulder&amp;stateOrProvince&#x3D;CO&amp;searchRadius&#x3D;150&amp;countryCode&#x3D;US
  # @param carrier Either \&quot;FedEx\&quot; or \&quot;UPS\&quot;
  # @param zip_code Required query parameter representing postal code
  # @param street_address Required param to add precision to the search
  # @param city Required param for city name
  # @param country_code Required two digit country code
  # @param state_or_province Required two digit state code
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :search_radius Optional parameter that indicates mile radius for search. Defaults to 10
  # @return [ShipCompliantRestAPIMiddlewaresSwaggerResponseTypesGetHoldLocationResponse]
  describe 'api_v1_hold_locations_carrier_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
