=begin
#ShipCompliant Connect

#ShipCompliant REST API supporting eCommerce and Point of Sale workflows. <br /> * required fields.

The version of the OpenAPI document: v1
Contact: shipcompliantsupport@sovos.com
Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::WholesaleInvoicesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'WholesaleInvoicesApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::WholesaleInvoicesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WholesaleInvoicesApi' do
    it 'should create an instance of WholesaleInvoicesApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::WholesaleInvoicesApi)
    end
  end

  # unit tests for api_v1_wholesale_invoices_post
  # Commits a new Wholesale Invoice to the system
  # Sample request:                 POST /api/v1/wholesaleInvoices   {         \&quot;PersistOption\&quot;: \&quot;OverrideExisting\&quot;,       \&quot;Order\&quot;: {           \&quot;BillingCustomerKey\&quot;: \&quot;Billing123\&quot;,           \&quot;ExternalSalesOrderKey\&quot;: \&quot;External123\&quot;,           \&quot;OrderNumber\&quot;: \&quot;Order123\&quot;,           \&quot;OrderReserved\&quot;: \&quot;Order123\&quot;,           \&quot;ReferenceNumber\&quot;: \&quot;Reference123\&quot;,           \&quot;RefundedOrderReference\&quot;: \&quot;RefundedOrder123\&quot;,           \&quot;Shipments\&quot;: [           {               \&quot;DefaultWarehouse\&quot;: \&quot;WineShipping\&quot;,               \&quot;Freight\&quot;: 0.00,               \&quot;ShipDate\&quot;: \&quot;2020-11-01T00:00:00Z\&quot;,               \&quot;ShipmentItems\&quot;: [               {                   \&quot;BrandKey\&quot;: \&quot;Brand123\&quot;,                   \&quot;FobPointKey\&quot;: \&quot;FOB\&quot;,                   \&quot;ItemReserved\&quot;: \&quot;ItemReserved\&quot;,                   \&quot;ProductKey\&quot;: \&quot;Product123\&quot;,                   \&quot;Quantity\&quot;: 1,                   \&quot;QuantityType\&quot;: \&quot;CASE\&quot;,                   \&quot;UnitPrice\&quot;: 19.99               }               ],               \&quot;ShipmentKey\&quot;: \&quot;1\&quot;,               \&quot;ShipmentReserved\&quot;: \&quot;ShipmentReserved\&quot;,               \&quot;ShippingCustomerKey\&quot;: \&quot;Shipping123\&quot;,               \&quot;ShippingService\&quot;: \&quot;FEX\&quot;           }           ],           \&quot;Tags\&quot;: [           {               \&quot;Name\&quot;: \&quot;Test Tag\&quot;           }           ],           \&quot;TransactionDate\&quot;: \&quot;2020-11-01T00:00:00Z\&quot;,           \&quot;TaxCollected\&quot;: 0.00       }   }
  # @param [Hash] opts the optional parameters
  # @option opts [ShipCompliantRestAPIDomainsWholesaleEntitiesPostInvoiceInput] :ship_compliant_rest_api_domains_wholesale_entities_post_invoice_input The new order
  # @return [ShipCompliantRestAPIMiddlewaresSwaggerResponseTypesPostWholesaleInvoiceResponse]
  describe 'api_v1_wholesale_invoices_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
