=begin
#ShipCompliant Connect

#ShipCompliant REST API supporting eCommerce and Point of Sale workflows. <br /> * required fields.

The version of the OpenAPI document: v1
Contact: shipcompliantsupport@sovos.com
Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::ShipCompliantRestAPIDomainsSalesOrderEntitiesTaxRateAddressOutput
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::ShipCompliantRestAPIDomainsSalesOrderEntitiesTaxRateAddressOutput do
  let(:instance) { OpenapiClient::ShipCompliantRestAPIDomainsSalesOrderEntitiesTaxRateAddressOutput.new }

  describe 'test an instance of ShipCompliantRestAPIDomainsSalesOrderEntitiesTaxRateAddressOutput' do
    it 'should create an instance of ShipCompliantRestAPIDomainsSalesOrderEntitiesTaxRateAddressOutput' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::ShipCompliantRestAPIDomainsSalesOrderEntitiesTaxRateAddressOutput)
    end
  end

  describe 'test attribute "address_status"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["Null", "AddressOutOfRange", "AddressSuggested", "ComponentMismatch", "MultipleMatches", "NonDeliverableAddress", "NoStreetData", "UnknownStreet", "Validated", "ZipCodeDoesNotExist", "ZipCodeDoesNotMatchCityState"])
      # validator.allowable_values.each do |value|
      #   expect { instance.address_status = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "city"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "county"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "state"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "street1"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "street2"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "zip1"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "zip2"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
