=begin
#ShipCompliant Connect

#ShipCompliant REST API supporting eCommerce and Point of Sale workflows. <br /> * required fields.

The version of the OpenAPI document: v1
Contact: shipcompliantsupport@sovos.com
Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::ShipCompliantRestAPIDomainsSalesOrderEntitiesShipmentSalesTaxRate
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::ShipCompliantRestAPIDomainsSalesOrderEntitiesShipmentSalesTaxRate do
  let(:instance) { OpenapiClient::ShipCompliantRestAPIDomainsSalesOrderEntitiesShipmentSalesTaxRate.new }

  describe 'test an instance of ShipCompliantRestAPIDomainsSalesOrderEntitiesShipmentSalesTaxRate' do
    it 'should create an instance of ShipCompliantRestAPIDomainsSalesOrderEntitiesShipmentSalesTaxRate' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::ShipCompliantRestAPIDomainsSalesOrderEntitiesShipmentSalesTaxRate)
    end
  end

  describe 'test attribute "freight_sales_tax_rate"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "product_sales_tax_rates"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "shipment_key"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
