=begin
#ShipCompliant Connect

#ShipCompliant REST API supporting eCommerce and Point of Sale workflows. <br /> * required fields.

The version of the OpenAPI document: v1
Contact: shipcompliantsupport@sovos.com
Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::ShipCompliantRestAPIDomainsSalesOrderResponsesShipmentComplianceResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::ShipCompliantRestAPIDomainsSalesOrderResponsesShipmentComplianceResponse do
  let(:instance) { OpenapiClient::ShipCompliantRestAPIDomainsSalesOrderResponsesShipmentComplianceResponse.new }

  describe 'test an instance of ShipCompliantRestAPIDomainsSalesOrderResponsesShipmentComplianceResponse' do
    it 'should create an instance of ShipCompliantRestAPIDomainsSalesOrderResponsesShipmentComplianceResponse' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::ShipCompliantRestAPIDomainsSalesOrderResponsesShipmentComplianceResponse)
    end
  end

  describe 'test attribute "compliance_status"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["Compliant", "NotCompliant", "Bypassed"])
      # validator.allowable_values.each do |value|
      #   expect { instance.compliance_status = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "key"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "rules"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
