=begin
#ShipCompliant Connect

#ShipCompliant REST API supporting eCommerce and Point of Sale workflows. <br /> * required fields.

The version of the OpenAPI document: v1
Contact: shipcompliantsupport@sovos.com
Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::ShipCompliantRestAPIDomainsSalesOrderEntitiesSalesTaxRates
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::ShipCompliantRestAPIDomainsSalesOrderEntitiesSalesTaxRates do
  let(:instance) { OpenapiClient::ShipCompliantRestAPIDomainsSalesOrderEntitiesSalesTaxRates.new }

  describe 'test an instance of ShipCompliantRestAPIDomainsSalesOrderEntitiesSalesTaxRates' do
    it 'should create an instance of ShipCompliantRestAPIDomainsSalesOrderEntitiesSalesTaxRates' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::ShipCompliantRestAPIDomainsSalesOrderEntitiesSalesTaxRates)
    end
  end

  describe 'test attribute "recommended_sales_tax_due"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "retail_delivery_fees"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "shipment_sales_tax_rates"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
