=begin
#ShipCompliant Connect

#ShipCompliant REST API supporting eCommerce and Point of Sale workflows. <br /> * required fields.

The version of the OpenAPI document: v1
Contact: shipcompliantsupport@sovos.com
Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::ShipCompliantRestAPIDomainsSalesOrderEntitiesCustomerAggregateVolumeLimitDetail
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::ShipCompliantRestAPIDomainsSalesOrderEntitiesCustomerAggregateVolumeLimitDetail do
  let(:instance) { OpenapiClient::ShipCompliantRestAPIDomainsSalesOrderEntitiesCustomerAggregateVolumeLimitDetail.new }

  describe 'test an instance of ShipCompliantRestAPIDomainsSalesOrderEntitiesCustomerAggregateVolumeLimitDetail' do
    it 'should create an instance of ShipCompliantRestAPIDomainsSalesOrderEntitiesCustomerAggregateVolumeLimitDetail' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::ShipCompliantRestAPIDomainsSalesOrderEntitiesCustomerAggregateVolumeLimitDetail)
    end
  end

  describe 'test attribute "customer_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["Null", "Household", "Individual"])
      # validator.allowable_values.each do |value|
      #   expect { instance.customer_type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "time_frame_count"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "time_frame_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["Calendar", "Rolling"])
      # validator.allowable_values.each do |value|
      #   expect { instance.time_frame_type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "time_frame_unit"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["Null", "Minutes", "Hours", "Days", "Weeks", "Months", "Years"])
      # validator.allowable_values.each do |value|
      #   expect { instance.time_frame_unit = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "unit_of_measure"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["Null", "Bottle", "Case", "Gallon", "Liter", "Milliliter", "Ounce", "Quart", "Barrel"])
      # validator.allowable_values.each do |value|
      #   expect { instance.unit_of_measure = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "volume_count"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
